#!/usr/bin/env python3
"""
project_restore.py

Restore a project from project_dump.txt generated by project_dump.py.

Usage:
    python project_restore.py

or

    python project_restore.py path/to/project_dump.txt

The project will be recreated in the folder where this script is executed.
"""

from pathlib import Path
import re
import sys

# ============================================================================
# Configuration
# ============================================================================

DEFAULT_DUMP_FILE = "project_dump.txt"

# Set to False if you don't want existing files overwritten.
OVERWRITE_EXISTING = True

# ============================================================================

FILE_MARKER = re.compile(r"^FILE:\s*(.+)$")


def restore_project(dump_file: Path, output_dir: Path):

    if not dump_file.exists():
        print(f"ERROR: Dump file not found: {dump_file}")
        return

    print("=" * 70)
    print("PROJECT RESTORE")
    print("=" * 70)
    print(f"Input : {dump_file}")
    print(f"Output: {output_dir}")
    print()

    restored = 0
    skipped = 0

    current_file = None
    current_lines = []
    collecting = False

    with open(dump_file, "r", encoding="utf-8", errors="ignore") as f:

        for line in f:

            line = line.rstrip("\n")

            # -----------------------------------------------------------------
            # Detect FILE:
            # -----------------------------------------------------------------
            match = FILE_MARKER.match(line)

            if match:

                # Save previous file
                if current_file is not None:

                    save_file(
                        output_dir,
                        current_file,
                        current_lines,
                    )

                    restored += 1

                current_file = Path(match.group(1).strip())
                current_lines = []
                collecting = False
                continue

            # Ignore separator lines
            if line.startswith("#") and len(line) > 20:
                collecting = True
                continue

            if current_file is None:
                continue

            if not collecting:
                continue

            current_lines.append(line)

    # Save last file
    if current_file is not None:

        save_file(
            output_dir,
            current_file,
            current_lines,
        )

        restored += 1

    print()
    print("=" * 70)
    print(f"Files Restored : {restored}")
    print(f"Files Skipped  : {skipped}")
    print("=" * 70)
    print("Done.")


def save_file(base: Path, relative: Path, lines):

    target = base / relative

    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists() and not OVERWRITE_EXISTING:
        print(f"Skip : {relative}")
        return

    # Remove trailing blank lines
    while lines and lines[-1] == "":
        lines.pop()

    with open(target, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Created : {relative}")


def main():

    if len(sys.argv) > 1:
        dump_file = Path(sys.argv[1])
    else:
        dump_file = Path(DEFAULT_DUMP_FILE)

    output_dir = Path.cwd()

    restore_project(
        dump_file=dump_file,
        output_dir=output_dir,
    )


if __name__ == "__main__":
    main()